### ISSUE TITLE
hi i am using your shader in my project mate thanks

### ISSUE THREAD

**Issue by ArslanAkhtar** [jonas-johansson/ARCoreUtils#1]
the only issue i am getting the shadow is pix-elated

**Comment by ArslanAkhtar** [comment]
could you please help from where i can improve quality

**Comment by jonas-johansson** [comment]
Tip for the shadows: use "close" instead of "stable", make sure the default quality setting for Android is high (change default with the little down arrow under Android in Quality Settings), and make sure the directional light is set up to use the quality settings.

You can dig around in the demo scene and project settings if you want to have a look at it.
