### ISSUE TITLE
Visualizer plane is not rendering properly

### ISSUE THREAD

**Issue by bpca17** [jonas-johansson/ARCoreUtils#6]
Hi,

After enabling ARSurfaceManager prefab, the plane visualizer thing not rendering properly.
When I disable your prefab, everything is fine.
Please help me with this.
Your plugin is awesome.

I am using Samsung Galaxy S7 device for testing.
Attached is the screenshot.
![screenshot_20180413-174144](https://user-images.githubusercontent.com/9516026/38734313-bbe7c4cc-3f42-11e8-8465-7e43592b13d6.png)

Thanks,
Bhanu.

**Comment by jonas-johansson** [comment]
Hi,

I just pushed a new commit to help you out:

> Raised the ARSurface up slightly to avoid flickering for those who render additional geometry beneath the ARSurface.

The reason for the flickering is because the shadow is actually rendered on invisible geometry - I call that invisible surface the _ARSurface_. Because you have the plane visualizer on at the same time at the exact same place you would get the result you see because of depth fighting.

**Comment by bpca17** [comment]
If I take the update, Will it render properly?


Thanks,
Bhanu.

**Comment by jonas-johansson** [comment]
There's only one way to find out - try it ;). It should hopefully work.
